Lambda-School-Labs/family-promise-service-tracker-fe-a

src/components/common/Navbar/HamburgerMenu.js
src/components/common/Navbar/NavbarHeader.js
src/components/common/Navbar/navbar.css
src/components/common/index.js
src/components/pages/Employees/EmployeesContainer.js
src/components/pages/Employees/RenderEmployeesPage.js
src/components/pages/Employees/index.js
src/components/pages/Home/RenderHomePage.js
src/components/pages/MyProfile/MyProfileContainer.js
src/components/pages/MyProfile/RenderMyProfile.js
src/components/pages/MyProfile/index.js
src/components/pages/Programs/ProgramsContainer.js
src/components/pages/Programs/RenderProgramsPage.js
src/components/pages/Programs/index.js
src/components/pages/Recipients/RecipientsContainer.js
src/components/pages/Recipients/RenderRecipientsPage.js
src/components/pages/Recipients/index.js
src/components/pages/Services/RenderServicesPage.js
src/components/pages/Services/ServicesContainer.js
src/components/pages/Services/index.js
src/index.js

Created Routes to all pages in application, created hamburger menu bar and header for tablet view

Feauture/menu bar/hali

---

src/styles/theme-overrides.js

Added our primary colors into the global themes.

Added Primary Color and Link color to be our decided color

---

package-lock.json
package.json
src/state/actions/index.js
src/state/actions/serviceActions.js
src/state/actions/userActions.js
src/state/index.js
src/state/reducers/index.js
src/state/reducers/serviceReducer.js
src/state/reducers/userReducer.js

Created Service Actions and Service Reducers. Added service reducer to root reducer by using combineReducer Hook

State management/redux

---

package-lock.json
package.json
src/components/pages/Recipients/RenderRecipientsPage.js
src/components/pages/Services/RenderServicesPage.js
src/components/pages/Services/form-service/FormContainer.js
src/components/pages/Services/form-service/index.js
src/components/pages/Services/form-service/renderServiceForm.js

Created service-form folder with ANTD Form for Service Entries.

Feature/services form/ruben ramirez

---

docs/pull_request_template.md

We should all be using this template.

Created PR Template for Front-End

---

src/components/pages/Services/RenderServicesPage.js
src/index.js

Fixed file name which was cuasing app to not compile
Fix App

Service-Form Rendering

---

src/components/common/Navbar/HamburgerMenu.js
src/components/pages/MyProfile/MyProfileContainer.js

Feature/my profile/hali

---

src/components/common/Title.js
src/components/pages/MyProfile/MyProfileContainer.js
src/components/pages/Programs/ProgramsContainer.js
src/components/pages/Programs/RenderProgramsPage.js
src/components/pages/Services/RenderServicesPage.js
src/components/pages/Services/ServicesContainer.js
src/styles/commonComponents.scss

I created a Dynamic Title Component with TitleText being the prop.
This was done for consistency throughout the project using reusable components. 
No particular user story, but overall styling of project. 
[] New feature (non-breaking change which adds functionality)
Change Status
[] Yes
[x] My code has been reviewed by at least one peer
[x] I have commented my code, particularly in hard-to-understand areas
[x] I have made corresponding changes to the documentation
[x] My changes …

Dynamic Title Component with TitleText being the prop

---

src/components/forms/AddProgramForm.js

Drop down Field for Program Types
Change Status
[] Completed, ready to review and merge
[] My code follows the style guidelines of this project
[] I have performed a self-review of my own code
[] My code has been reviewed by at least one peer
[] I have commented my code, particularly in hard-to-understand areas
[] I have made corresponding changes to the documentation
[] My changes generate no new warnings
[] There are no merge conflicts

Changed program type field to dropdown select

---

src/components/common/Navbar/HamburgerMenu.js

Changed navbar icon as requested by David. 
Better to use regular hamburger menu

Changed Menu Icon

---

src/components/common/Navbar/HamburgerMenu.js
src/components/common/Navbar/NavbarHeader.js
src/components/pages/Employees/EmployeesContainer.js
src/components/pages/MyProfile/MyProfileContainer.js
src/components/pages/Programs/ProgramsContainer.js
src/components/pages/Recipients/RecipientsContainer.js
src/components/pages/Services/ServicesContainer.js
src/index.js

Fixed Navbar so it renders only once and 
[] Bug Fix
Change Status
[] Completed, ready to review and merge

Bug fix/navbar

---

src/components/forms/AddServiceForm.js
src/components/forms/AddServiceTypeForm.js
src/components/pages/Services/RenderServicesPage.js
src/components/pages/Services/ServicesContainer.js
src/styles/Services.scss

I added a 'Add Service Type' button on the Render Service Page that brings up the modal. I added a visibleType state as well. 
Service Types CRUD operations will be handled by Admin and Program Managers. This button and modal is how they will do it. 
(Link if possible)[https://trello.com/c/qB7xchqU]
[x] New feature (non-breaking change which adds functionality)
Change Status
[] Yes
[] My code has been reviewed by at least one peer
[x] I have …

Added Service Type Modal and Button

---

src/components/common/Table/Dropdown.js
src/components/common/Table/Tags.js
src/components/pages/Employees/EmployeesContainer.js
src/components/pages/Employees/RenderEmployeesPage.js
src/index.js
src/styles/styles.less

When merging table, alot of things got broke. Deleetd less files and react-tween import that wasn't allowed by Lambda school. Then cleaned up errors and bugs from tables. This is the initial fix but there is still alot of work that needs to be done
Application was failing to compile
table feature
Change Status
[] Yes
[x] My code has been reviewed by at least one peer
[x] I have commented my code, particularly in hard-to-understand areas
[x] I have made corresponding …

fixed bugs w/tables, ready to work on tables

---

src/components/common/Table/Table.js
src/components/forms/AddEmployeeForm.js
src/components/pages/Employees/RenderEmployeesPage.js
src/state/reducers/employeeReducer.js

Changes were made to add employee form as well as the table component. 
The tags in our table needed to be color coordinated, the roles associated with employees needed to be mapped to our form values. The data not being rendered on the table was also fixed. 
[] New feature (non-breaking change which adds functionality)
Change Status
[] Yes
[] My code has been reviewed by at least one peer
[x] I have commented my code, …

Employeespg table jose

---

src/components/common/ProgramsTable/ProgramTable.js
src/components/common/ProgramsTable/Tags.js
src/components/forms/AddProgramForm.js
src/components/pages/Programs/ProgramsContainer.js
src/components/pages/Programs/RenderProgramsPage.js

The Program Table was connected to redux. Functionality for delete and add was completed. There still needs to be work on the rerendering. 
The Program table and functionality is MVP
As a Admin, I can CRUD Programs
[] New feature (non-breaking change which adds functionality) 
Edit functionality still needs work 
Change Status
[] Yes
[] My code has been reviewed by at least one peer
[x] I have commented my code, particularly in …

Added Program Table and Buttons

---

src/components/common/ProgramsTable/ProgramTable.js
src/state/actions/programActions.js

Full functionality for the program page: add programs, edit programs in table and delete program
This was one of the MVPs required. 
[] New feature (non-breaking change which adds functionality)
Change Status
[] Completed, ready to review and merge
[] Yes
[x] My code has been reviewed by at least one peer
[x] I have commented my code, particularly in hard-to-understand areas
[x] I have made corresponding changes to the documentation
[x] My changes generate no new warnings
[x] There …

100% functionality on Program page

---

src/components/common/ProgramsTable/ProgramTable.js
src/state/reducers/employeeReducer.js
src/state/reducers/programReducer.js
src/state/reducers/serviceReducer.js
src/state/reducers/serviceTypeReducer.js

Within the reducer file, I added another new key within the initialState object to keep track of changes made. Within the successful cases, I changed the key, "change"  to be what had occurred i.e. "Added","Edited", "Deleted" and within the resolved cases, I returned it back to an empty string.  
I then connected the change state within the components so it could be monitored within the useEffect. 
This is an optimal way to re-render the component. Whenever a new CRUD operation occurred and succeeded, that change key would be updated, thus leading to the re-rendering of the component. 
[As an Administrator, I can view, create, edit and remove programs. ](https://trello.com/c/tuHmcfN3) 
**Any …

Redux Re-render Fix

---

.vscode/settings.json
src/state/actions/recipientActions.js
src/state/reducers/recipientReducer.js

- The work that was done was the creation of actions & reducers for the recipients. (GET, ADD, EDIT, DELETE)
- To add Redux functionality to the recipients, actions tell what to do and reducers tell it how to do it.
- This is part of this story: - AG FE: I can create a new recipient by filling out the form fields with appropriate information
- New feature (non-breaking …

action and reducers made for recipients

---

src/state/actions/index.js
src/state/index.js
src/state/reducers/index.js

-  Added actions and reducers to the index.js files
Testing
Change Status …

Added actions and reducer to index.js

---

src/components/common/RecipientsTable/RecipientTable.js
src/components/pages/Recipients/RecipientsContainer.js
src/components/pages/Recipients/RenderRecipientsPage.js
src/state/actions/recipientActions.js

- Reviewed over Zoom call with three other members.
- What work was done is the recipient tables. Made the necessary columns and connected it to display the correct information inputted when a user clicks on the recipients tab. Those with permissions are able to add new recipients and it'll populate the table and render correctly.
- The purpose of this is so information can be gathered on who are the recipients that are partaking in our service programs and that info can be collected to put in a metric in the future. …

Render recipients

---

package-lock.json
src/components/common/ServicesTable/ServiceTable.js
src/components/forms/AddServiceForm.js
src/components/forms/AddServiceTypeForm.js
src/components/pages/Services/RenderServicesPage.js
src/state/actions/serviceActions.js
src/state/reducers/serviceReducer.js

- Invited Daniel for code review. We pair programmed the entire day.
- Log Service Form needed to have access to the Redux store and none of the application tabs were connected (recipients, service types, and service providers). 
- Currently, the service provider dropdown grabs all available service providers from the DB as selectable options. Up next, we tackle recipients and service types as available dropdown menus in the log service form.
- The purpose of this feature is to control the user input for logging service by pre-filling the available options for the service provider, the recipient, and the service type involved. This leads to a system where incorrect entries cannot exist.
**What feature …

Log Services Form - Redux integrations with Service Providers now works as a dropdown.

---

src/components/common/Navbar/HamburgerMenu.js
src/styles/Layout.scss

Added a breakpoint to hide the menu automatically at around tablet size, I deleted a lot of the previous code because it looks like it was just duplicated and not used.  After deleting the previous code there were no errors or conflicts that came up on my end. 
https://user-images.githubusercontent.com/64627086/117870912-99f50980-b251-11eb-907f-8052259ac454.mp4

Changed the burger menu setup a bit so that theres a

---

src/state/reducers/recipientReducer.js

- Collaborated over Zoom with Andrew Sohrabi
- modified the recipient reducer so it can hit the backend data properly.
- for the recipient data to show up
Testing
Change Status …

Made changes to reducer so it will hit the backend

---

src/components/common/RecipientsTable/RecipientTable.js

- Modified the table, specifically the columns for name to separate it out to first_name and last_name to correctly match the recipient forms and backend.
- To make it look cleaner, especially when we do a service log or metric data for families.
Testing
- Has …

seperated name to first_name and last_name

---

src/state/index.js

- Describe in detail what's been modified/created - reducer changes
- What is the purpose of the feature? - Fixes Reducers
Testing
- YES
Change Status
- I have commented my code, particularly in …

Fixes Redux State issue within Services

---

src/components/common/RecipientsTable/RecipientTable.js

- Collaborated on Zoom
- Fixed the recipient table bug regarding editing a specific recipient
- To edit a recipient
Testing
Change Status
- My code follows the style guidelines …

changed allowing the recipients to be edited

---

src/__tests__/AddServicesTypeForm.test.js

Making test for addserviceTypeForm seeing it renders when called in test. 
Im not done with the test yet.
Testing
Change Status
- My code follows the style guidelines of this …

working on test for add serviceTypeForm getting form to render first

---

src/__tests__/AddServicesTypeForm.test.js
src/__tests__/RenderServicesPage.test.js

Testing to see if services page is rendering. Not finished yet.
Testing
Change Status
- I have performed a self-review of …

Feature/servicespage test/chasesnider

---

src/components/common/RecipientsTable/RecipientTable.js

- Made filter options for the recipient columns.
- To filter out specific recipients for basic functionality.
- As a user, I can filter the recipient table
Testing
Change Status …

Recipient table filter

---

src/components/common/ServicesTable/ServiceTable.js

-Invited Daniel
- added filters to ant d table in services
- outstanding: fix date filter
- To allow users to filter without making additional API calls
As a user, I can filter Services as needed.
Testing
-  Tested, no conflicts
Change Status
- My …

Filters for Service Table

---

src/__tests__/AddServicesTypeForm.test.js

working on test for addservicetypeform

---

src/__tests__/AddServicesTypeForm.test.js

Test update

---

src/components/forms/AddRecipientForm.js
src/components/pages/Recipients/RenderRecipientsPage.js
src/state/actions/recipientActions.js

- fixed recipient actions to stop the error that happened when you tried to edit recipients (changes still don't show up)
- connected households to recipient form so users can select from the existing households when creating a new user
- bug fixes
Testing
Change Status
- Completed, ready to review and …

Bug fix/recipients page

---

src/components/common/RecipientsTable/RecipientTable.js

- Cleaned out commented code
- To make the code look cleaner
Testing
Change Status
- I have performed a self-review of my …

Cleaned out the commented code

---

src/components/common/ServicesTable/ServiceTable.js
src/components/pages/Services/RenderServicesPage.js
src/state/reducers/serviceReducer.js

- Cleaned the code up and made some progress on the edit bugs. Documented outstanding issues in our Known defects file on Github.
Testing
- Tested before and after merge.
Change Status

Code cleanup + slight changes to edit functionality

---

src/state/actions/serviceActions.js
src/state/reducers/serviceReducer.js

Fixes the actions and reducers for adding new service entries.
To fix the bug where adding a new service entry wouldn't properly update the redux store and therefore not show the changes to the end user.

fixes broken service entry actions and reducer

---

src/components/common/Navbar/HamburgerMenu.js
src/components/common/Navbar/NavbarHeader.js
src/components/common/ProgramsTable/ProgramTable.js
src/components/common/ProgramsTable/Tags.js
src/components/common/RecipientsTable/RecipientTable.js
src/components/common/ServicesTable/ServiceTable.js
src/components/common/Table/Checkbox.js
src/components/common/Table/Table.js
src/components/forms/AddHouseholdForm.js
src/components/forms/AddProgramForm.js
src/components/forms/AddRecipientForm.js
src/components/forms/AddServiceForm.js
src/components/forms/AddServiceTypeForm.js
src/components/pages/Employees/RenderEmployeesPage.js
src/components/pages/MyProfile/MyProfileContainer.js
src/components/pages/MyProfile/RenderMyProfile.js
src/components/pages/Programs/ProgramsContainer.js
src/components/pages/Programs/RenderProgramsPage.js
src/components/pages/Recipients/RecipientsContainer.js
src/components/pages/Recipients/RenderRecipientsPage.js
src/components/pages/Services/RenderServicesPage.js
src/components/pages/Services/ServicesContainer.js
src/const.js
src/index.js
src/state/actions/serviceActions.js
src/state/index.js

Cleaning up the dozens and dozens of errors, warnings, and console logs throughout the app. Some actual user-facing bugs were also uncovered and fixed, but this was primarily to clean up the console. 
To make development life easier

Fix React warnings, errors and various extraneous console logs

---

src/components/common/Navbar/NavbarHeader.js
src/components/common/ServicesTable/ServiceTable.js
src/components/pages/Recipients/RenderRecipientsPage.js
src/components/pages/Services/RenderServicesPage.js
src/components/pages/Services/ServicesContainer.js
src/state/reducers/serviceReducer.js
src/styles/Programs.scss
src/styles/Services.scss

- Lots of updates made to the service entry table to improve usability and fix bugs 
- - Consolidated fields like names & address to make everything viewable on tablet
- - fixed all sorting bugs
- - fixed filtering bugs and implemented some basic filters
- - fixed all bugs that were preventing editing of records
- - reorders columns to improve legibility based on what's most likely information to be used
- Additionally made small layout changes across the app for button placement consistency to make it easier to use
- To make the service entries table usable

Feature/service entry UI

---

src/components/common/ServicesTable/ServiceTable.js
src/styles/Services.scss

- Updates layout of action column to make sure buttons are always on screen within the column.
- Change notes input to text area
- increases button size of action elements
- To improve usability of services table

fixes layout issues of edit/save/delete buttons

---

src/components/pages/MyProfile/RenderMyProfile.js

app crashes when trying to display a profile with no assigned programs
it now checks if the user has any programs before trying to map

fixes a crash when trying to display some profiles

---

src/components/pages/MyProfile/RenderMyProfile.js

- Changed the ternary operation to display data only if there it information to display on the RenderMyProfile.js
- Necessary for basic usage
Testing
Change Status
- I have performed a self-review of my own …

Bug fix on profile

---

src/components/common/MyProfileComponent.js
src/components/pages/Dashboard/DashboardContainer.js
src/components/pages/Dashboard/RenderDashboardPage.js
src/styles/commonComponents.scss

- Created the whole component and added it to the dashboard page.
- Managed the state so it dynamically changes for each user
- Remaining work is to style the component,
- display metrics on the user and current user
*https://trello.com/c/1AaSfP9i
Testing
Change Status
- My …

Basic structure for MyProfile card on dashboard

---

src/app.scss
src/components/forms/AddEmployeeForm.js
src/components/forms/AddHouseholdForm.js
src/components/forms/AddProgramForm.js
src/components/forms/AddRecipientForm.js
src/components/forms/AddServiceForm.js
src/components/forms/AddServiceTypeForm.js

- add placeholders to all inputs in all modals
- modified some styling for uniformity. 
- There were some inputs missing placeholders 
Change Status
- My changes generate no new warnings
- There are no merge conflicts

add uniform placeholders and styling to modals

---

src/app.scss

- Weston
- a media query was added to app.scss that makes the font slightly larger
- To optimize the app for tablet view
Optimize the app for tablet-size
- Styling updated
Change Status

improved font readability for tablet-view

---

src/components/common/Navbar/HamburgerMenu.js
src/components/common/Navbar/NavbarHeader.js
src/index.js

- When a user clicks on the logo it links back to that user's dashboard
- When a user clicks on the logo it links back to that user's dashboard
When a user clicks on the logo it links back to that user's dashboard
Testing
X Has this feature been tested before conflict?
Change Status
X Completed, ready to review and merge
XMy changes generate no new warnings
X There are no merge conflicts

Logo routing/robert allen

---

src/components/common/Navbar/NavbarHeader.js
src/index.js

When an admin logs in they get taken to the dashboard instead of profile page
The user / admin was being directed to their profile before which seemed pointless. 
Change Status
XMy changes generate no new warnings
X There are no merge conflicts

Frontend/admin routing/robert allen

---

src/components/pages/Dashboard/DashboardContainer.js
src/components/pages/Dashboard/ServiceTable.js

- Added a Services Table to the dashboard
- The purpose was to flesh out the dashboard
Testing
Change Status
- My code has …

Feature services table

---

src/app.scss
src/components/common/Navbar/HamburgerMenu.js
src/styles/Layout.scss
src/styles/NavBar.scss

- I have modified the navbar to have logo and profile on the top and the rest of pages on the bottom. 
- The purpose of this feature was to create a more responsive design towards ipads. 
https://trello.com/c/KREE0Y2j and 
Testing
Change Status …

new navbar completed for ipad and desktop

---

src/app.scss
src/components/common/Navbar/HamburgerMenu.js
src/components/common/Navbar/NavbarHeader.js
src/components/pages/Programs/RenderProgramsPage.js
src/index.js
src/styles/NavBar.scss

- Fixed missing profile page component
- Fixed navbar horizontal scrolling( margins problem)
- Fixed program page sending you back to dashboard when you are manager or administrator. 
- Fixing main functional issues
- Quick Fix
Change Status
- My changes generate no new warnings
- There are no merge conflicts

Important Fixes

---

src/app.scss
src/components/common/MetricsFilterBar/MetricsFilterBar.js
src/components/common/RecipientsTable/RecipientTable.js
src/components/pages/Dashboard/DashboardContainer.js
src/components/pages/Dashboard/RenderDashboardPage.js
src/styles/Dashboard.scss
src/styles/NavBar.scss
src/styles/Recipients.scss

- Centered dropworn menus and gave them space between them
- Cleaned space between recipients table and edge of screen
- Moved arrows on the bottom to the center
- Added recipients style sheet for future changes
- Restyled myProfile Component
https://trello.com/c/B20uLLEB
Change Status
- My changes generate no new warnings
- There are no merge conflicts

Responsive Design Changes

---

src/components/pages/Programs/RenderProgramsPage.js

- Fixed function that would send you back to dashboard when trying to see the programs page. 
- Necesary urgent fix

fixed programs function to work as intended

---

src/state/actions/employeeActions.js
src/state/actions/serviceActions.js
src/state/actions/userActions.js

fixed endpoint urls

---

src/components/common/Navbar/HamburgerMenu.js
src/components/forms/AddCategoryForm.js
src/components/pages/Categories/Categories.js
src/components/pages/Categories/index.js
src/index.js

- Added Categories tabs to begin the new feature for the categories table

add properties tab

---

src/components/forms/AddCategoryForm.js
src/components/pages/Categories/Categories.js

added a dropdown of list of programs from programs
CategoriesForm dropdown
add list of programs
Change Status
x My code follows the style guidelines of this project
x I have performed a self-review of my own code
x My code has been reviewed by at least one peer
x I have commented my code, particularly in hard-to-understand areas
x I have made corresponding changes to the documentation
x My changes generate no new warnings
x There are no merge conflicts

Categorie dropdown modal/robert allen

---

src/components/common/MetricsFilterBar/MetricsFilterBar.js
src/components/common/Navbar/HamburgerMenu.js
src/components/common/Navbar/NavbarHeader.js
src/components/common/RecipientsTable/RecipientTable.js
src/components/common/ServicesTable/ServiceTable.js
src/components/forms/AddRecipientForm.js
src/components/pages/Recipients/RenderRecipientsPage.js

- Changed profile icon to an avatar
- Deleted extra console logs
- Clean up and styling

"Changed profile icon to an avatar and deleted console logs"

---

src/components/common/MetricsFilterBar/MetricsFilterBar.js
src/components/common/MetricsFilterBar/MetricsSelected.js

Created a new component that renders under the filter bar. The new component is used show the user the names of the selected items from the dropdown menu. Sorry I know it's a lot with no commits, I had some git issues and ended up having to terminate the old branch quite a ways through
Jonathan1600
JasonCorchado
robertjallen
-I constructed a component which takes in the selected value off a dropdown as props and displays the information back to the user underneath the filter bar.
- To match the designed dashboard layout provided for us. This will ultimately make it more clear for a user to understand which metrics are being shown to the them via graphs/tables. …

displays metrics selected from filter bar

---

src/components/common/ProgramsTable/ProgramTable.js

- Delete operation now points to correct column
- In order to fix delete operation in the Programs Feature.
- Programs Feature
- Fixed feature
Testing
Change Status
- I have made corresponding changes to the …

Fixed merge conflict

---

package-lock.json
src/components/forms/AddServiceForm.js

Within the log a service form, reorganized ANT library fields and renamed ANT library labels/field names so users / service providers can understand forms faster and navigate through them quicker
so users / service providers can understand forms faster and navigate through them quicker
the overarching feature is a core function of the app, allowing service providers to log work being done via tablet on-site, whereas this PR is regarding improving the overarching feature by improving UX
https://trello.com/c/vQFxOpI6
Organized/Named This Way Now:
Date & Time of Service
Service Type
Service Status …

Log A Service Form - Reorganized / Renamed Fields For Easy Understanding

---

src/components/common/ServicesTable/ServiceTable.js
src/components/forms/AddServiceForm.js

- Service Status rendered on screen
- Service Status filtering fixed
- Service Notes rendered on screen
- create better viewing experience for user
- https://trello.com/c/M1ikcPZN/64-as-an-authorized-user-i-can-filter-the-service-logs-by-a-status-or-statuses
- https://trello.com/c/qLN81VxZ/54-as-a-service-provider-or-other-authorized-user-i-can-use-a-tablet-to-log-a-new-service-that-was-provided-to-a-recipient-and-see
- 
Testing
- 
Change Status
- I have commented …

Feature/service table/m habermas

---

src/components/forms/AddServiceForm.js

in the log service form set the form value and quantity fields to accept only numbers
avoid letters being entered into value and quantity fields 
Testing
- Has this feature been tested before conflict? yes
- Has this feature been tested after conflict? yes
Change Status
- …

changed quantity&value form type to type="number"

---

src/components/common/ServicesTable/ServiceTable.js
src/components/forms/AddRecipientForm.js
src/components/forms/AddServiceForm.js
src/state/actions/serviceActions.js

- Fixed date sort on services screen
- make it easier to see what service was provided when
https://trello.com/c/SNoCMFr5/59-as-an-authorized-user-i-can-filter-the-logged-services-by-the-dates-on-which-they-were-provided
- Bug fix
Testing
Change Status
- My code has been reviewed by at …

Feature/date sort/mhabermas

---

src/components/common/ServicesTable/ServiceTable.js

- fixed service tab service type sort
- enable user to organize data logs better
https://trello.com/c/UM3QaGpG/58-as-an-authorized-user-i-can-filter-the-service-logs-by-a-service-type-or-types
Testing
Change Status
- I have performed a self-review of my own …

Feature/service type sort/mhabermas

---

src/components/pages/Dashboard/DashboardHouseholdEligibility.js
src/components/pages/Dashboard/RenderDashboardPage.js
src/styles/Dashboard.scss

Created UI for eligibility dashboard on dashboard tab, allows you to enter household ID and get info back on whether a household is eligible for reduced bus fare / residential assistance
Does still need the proper DS URL for the axios get request that populates our component state with whether a household is eligible, DS almost has that ready (the eligibility model is already done on their end)
-created UI for eligibility section on dashboard tab
- created input form for household ID that we want to check eligibility of
- created display for displaying eligibility results
- as a user, I need to be able to check the eligibility of a household I'm helping or about to help
User Story: As a user, I …

Created Eligibility Section / Household ID Form / Eligibility Results Display On Dashboard Tab

---

src/components/common/ProgramsTable/ProgramTable.js

- fixed editing bug on programs page 
- made it so an individual entry could be addressed
Testing
Change Status
- …

fixed edit bug

---

src/components/pages/Dashboard/DashboardHouseholdEligibility.js
src/styles/Dashboard.scss

Got eligibility determination feature on dashboard tab working alongside DS team.  Now able to determine eligibility dynamically based on household ID input.
Connected DS Eligibility Deployed Endpoint (http://family-promise-dev.us-east-1.elasticbeanstalk.com/eligibility/) to frontend axios request within household eligibility component within dashboard group of components, insured data was being properly 
communicated through UI and showing yes/no response that's informative to user
Key feature request by stakeholder and allows our users to determine what services the people they help are eligible for, which is a requirement for them to be able to do their jobs
User Story: As an admin or program …

Got Eligibility Web Frontend Connected to DS Backend, Eligibility Feature Now Works

---

src/components/common/ServicesTable/ServiceTable.js
src/components/pages/Services/RenderServicesPage.js
src/components/pages/Services/ServicesContainer.js
src/styles/Dashboard.scss
src/styles/Services.scss

Created Service Tab  / Table Media Queries For Desktop Viewports / Large Viewports so that table column widths aren't excessively large and so that other elements on page align with new table/column widths.
Created media queries for browser viewports starting above 1025 px ranging up to 1600px, eliminated wild comma on services tab that was likely a typo
Improve the user experience on a key feature
Private slack discussion for all cohorts with pics:
https://lambda-students.slack.com/archives/C02AFKQBD2L/p1629406911374800
- Improving existing feature (non-breaking change which adds functionality)
Change Status
- My code follows the style guidelines of this …

UX - Created Service Tab  / Table Media Queries For Desktop Viewports / Large Viewports

---

src/components/common/Navbar/HamburgerMenu.js
src/components/common/Navbar/NavbarHeader.js

Fixed Nav
Testing
Change Status
- My changes generate no new warnings
- There are no merge conflicts

fixed navs

---

src/components/common/ServicesTable/ServiceTable.js
src/index.js

fixed thae display tab
Testing
Change Status
- I have made corresponding changes to the …

fixed ser ent tab display

---

src/state/reducers/serviceReducer.js

fixed get service success reducer bug, changed service to services

BugFix - Get Services Success Reducer Property Typo

---

src/components/pages/MyProfile/RenderMyProfile.js

--We were unable to view the MyProfile page.
--Jaden, Anthony, Kazden
-- Got rid of the index--we can't use an index to access an object
- What is the purpose of the feature?: 
--Bug fix--allowed us to view the Myprofile page
--As a user, it is important to access the profile page
--Bug fix
Testing
- …

Bug fix. Removed the attempt to access an object with an index.

---

src/components/common/Table/Table.js
src/components/pages/Employees/RenderEmployeesPage.js

Kazden, John and Anthony
I changed the word "Administrator" to be a 1 in the renderedEmployeesPage. This fixed an issue with authentication. I also changed the selectRole and userObjCreator functions in the table.js file to properly build the tableData array. the page now renders as expected.
Page was getting a lot of errors before, would not load. employees and programs were undefined. user access could not be granted to the page. 
To allow administrators access to a list of employees(providers) and to allow them to …

Provider bug fix

---

src/state/actions/index.js
src/state/actions/serviceUnitActions.js
src/state/actions/statusActions.js
src/state/index.js
src/state/reducers/index.js
src/state/reducers/serviceUnitReducer.js
src/state/reducers/statusReducer.js

Added GET ALL actions and reducers for status and service unit tables
- Anthony, Jaden, and John
- I added an action file with appropriate functionality regarding getting all statuses and service units. I also added reducer files/functionality for statuses and service units
- Prior to this update, this information was hardcoded in the frontend. 
[Trello Card](https://trello.com/c/GPafxkil)
Testing
- Has this feature been tested before conflict? No
- Has this feature been tested after conflict? Yes (tested manually)
Change Status
- Needs to be reviewed
- My code follows the style guidelines of this …

Feature/units and statuses Actions and Reducers

---

src/components/common/RecipientsTable/RecipientTable.js
src/components/forms/EditRecipientForm.js

* Originally, the front-end wasn't connecting the backend (save function wasn't being called), so connecting the two allowed us to pass in the form information instead of an empty object. 
We then worked to populate the form with the data of the recipient we clicked on: saved the record in state, passed state down to the form, and used InitialValue in each of the lines of the form. 
When exiting and going into a different recipient, the modal was not re-rendering despite the updated state. The ternary operator in the last commit triggered the necessary re-render.
**Why was this work …

Bugfix edit recipient form

---

src/components/forms/AddHouseholdForm.js
src/components/pages/Recipients/RenderRecipientsPage.js

- Added person to review relating to feature/bug-- yes
- I adjusted the addHouseholdForm.js to match what the BE was expecting. That allowed us to properly post to the BE.
****My first commit might not be necessary. I'm unsure if the form.resetFields() will update state, and cause the onCreate to pass an empty obj to the BE. I'm leaning towards it being an unnecessary change.
- The user was currently unable to add a new household, and now they will be able to do that.
**Any relevant links or images / …

Bugfix add household form.js

---

src/components/pages/Programs/RenderProgramsPage.js

Co-authored-by: John Laubscher jlmemphiscommanders@gmail.com
John Laubscher Anthony Cortese
- switched Administrator to role type of 1. 
- to allow access to the providers tab.
Provider screen could not be accessed because of this auth check.
Testing
- Has this …

made it so the programs page renders

---

src/components/forms/AddHouseholdForm.js

changed location_id from true to false

---

src/components/pages/Dashboard/DashboardContainer.js
src/components/pages/Dashboard/ServiceMap.js

Co-authored-by: Margarita Salazar <Margarita-Salazar@users.noreply.github.com>
Co-authored-by: Jasmine Lane-Garcia <JasmineLaneGarcia@users.noreply.github.com>
- [Loom summary](https://www.loom.com/share/afe5fd2803394fdaa7f7340e3ecd28f3)
Added map to Dashboard
- As a user I can view a map on my dashboard
- [Some relevant links or images / screenshots](https://whimsical.com/family-promise-W1z8vmBUSmA3mjreyZuFo2)
Change Status

Added base map to dashboard

---

src/components/pages/Dashboard/ServiceMap.js

- Cleaned up useless comments and added some clarification for ambiguous comments in ServiceMap.js 
- To clarify and direct future development
- Quality of life improvement 
Change Status

Cleaned up useless comments and added some clarification for ambiguous comments in ServiceMap.js
